name: Service Example

env:
  PROJECT: "DotnetServiceExample"
  
on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/shared/prepare-ruby
      - uses: ./.github/actions/shared/prepare-dotnet
      - name: package
        shell: bash
        run: ./run app:package
      - uses: actions/upload-artifact@v4
        with:
          name: lambda
          path: ${{ env.PROJECT }}/src/${{ env.PROJECT }}/bin/Release/net8.0/${{ env.PROJECT }}.zip
          
  deploy-staging:
    needs: [ package ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/shared/prepare-ruby
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: actions/download-artifact@v4
        with:
          name: lambda
      - name: Deploy
        shell: bash
        run: ./run service:provision[default]